Show posts by group - Front-end dropdown for groups on topic creation pop up inserted
CMU-313/spring24-nodebb-calisburgh pull request #15
Opened 2024-02-28 22:30 UTC by Jiatonglii22

Only front end code modified along with changing instances in some backend code.

nodebb-plugin-composer-default identified as the plugin responsible for generating Topic Creation Form/Pop up 

Created a copy and made modifications to it to include a second dropdown, later to be showing list of groups the user is in. 
Other changes involves changing instances of nodebb-plugin-composer-default to nodebb-plugin-composer-default-modified to get the code running and working.

2024-02-29 20:21 UTC, 0simoo requested changes
Same issue as #16
Looks like there are some linter issues, but there is also a problem in the Homework 1 check. I'm not sure if we'll get points taken off if we fail the check, but we are allowed to remove the hw1 tests, so it might be worth doing that just in case. Just go into .github/workflows and remove the hw1.yaml file to remove them.
We should get the linter issues fixed before merging, however.

2024-03-01 00:22 UTC, Jiatonglii22 commented
Linter errors resolved!

2024-03-01 01:06 UTC, 0simoo approved these changes

2024-03-01 01:27 UTC, kian-nick approved these changes
LGTM!

2024-03-01 02:08 UTC, merged