Show account type next to username
CMU-313/spring24-nodebb-calisburgh pull request #16
Opened 2024-02-28 22:37 UTC by Jiatonglii22

Account type was not shown on posts before. 

Now: 
<img width="1433" alt="Screenshot 2024-02-28 at 5 35 27 PM" src="https://github.com/CMU-313/spring24-nodebb-calisburgh/assets/102882840/f92b566d-d077-4dba-aac4-e3d8b288521e">

Instructors and students are indicated next to username 

Modifications made in themes/nodebb-theme-persona/templates/partials/topic/post.tpl to show accounttype for post user 
and backend code was modified slightly in src/topics/posts.js and src/posts/user.js to return accounttype information for the user.

2024-02-29 20:20 UTC, 0simoo requested changes
Looks like there are some linter issues, but there is also a problem in the Homework 1 check. I'm not sure if we'll get points taken off if we fail the check, but we are allowed to remove the hw1 tests, so it might be worth doing that just in case. Just go into .github/workflows and remove the hw1.yaml file to remove them.
We should get the linter issues fixed before merging, however.

2024-03-01 00:34 UTC, Jiatonglii22 commented
Linter errors resolved

2024-03-01 00:42 UTC, 0simoo approved these changes

2024-03-01 01:28 UTC, kian-nick approved these changes
LGTM!

2024-03-01 02:06 UTC, merged